[package]
name = "router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
http = ["axum", "axum-macros"]
p2p = ["prost", "grpc-libp2p"]
worker-registry = ["contract-client"]

[dependencies]
anyhow = "1"
aws-sdk-s3 = "0.21.0"
aws-config = "0.51.0"
clap = { version = "4.0.18", features = ["derive"] }
tokio = { version = "1.21.2", features = ["full"] }
url = "2.3.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3.0", features = ["env-filter", "json"] }
libc = "0.2"
lazy_static = "1.4.0"
prometheus = { version = "0.13.3", features = ["process"] }

router-controller = { version = "0.1", path = "../router-controller" }

# Http tranport
axum = { version = "0.5.17", optional = true }
axum-macros = { version = "0.2.3", optional = true }

# Libp2p transport
prost = { version = "0.11", optional = true }
grpc-libp2p = { version = "0.1", path = "../../../subsquid-network/grpc-libp2p", optional = true }

# Worker registry
contract-client = { version = "0.1", path = "../contract-client", optional = true }
