[package]
name = "archive-router-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
archive-router = { version = "0.1", path = "../archive-router" }

axum = "0.5.17"

