[package]
name = "archive-router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "1.2.1"
url = "2.3.1"
rand = "0.8.5"
